#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include<ctype.h>
void main()
{
FILE *fint,*ftab,*flen,*fsym,*fout;
int op1[10],txtlen,txtlen1,i=0,j=0,len;
char null0[10],null1[10],null2[10];
char add[5],symadd[5],op[5],start[10],temp[30],line[20],label[20],mne[10],operand[10],symtab[10],opmne[10];
fint=fopen("output.txt","r");
flen=fopen("lenght.txt","r");
ftab=fopen("optab.txt","r");
fsym=fopen("symtab.txt","r");
fout=fopen("pass2.txt","w");
while(!feof(fint)){
fscanf(fint,"%s%s%s%s",add,label,mne,operand);
if((strcmp(mne,"RESW")==0)||(strcmp(mne,"RESB")==0)||(strcmp(mne,"START")==0)||(strcmp(mne,"END")==0)) continue;
i++;
}
i=i*3;
fint=fopen("output.txt","r");
fseek(fint,SEEK_SET,0);
fscanf(fint,"%s%s%s%s",add,label,mne,operand);
if(strcmp(mne,"START")==0)
{
strcpy(start,operand);
fscanf(flen,"%s%s%s%d",null0,null1,null2,&len);
}
fprintf(fout,"H^%s^00%s^%06d",label,start,len);
fscanf(fint,"%s%s%s%s",add,label,mne,operand);
fprintf(fout,"\nT^00%s^%x",start,i);
while(strcmp(mne,"END")!=0)
{
fscanf(ftab,"%s%s",opmne,op);
while(!feof(ftab))
{
if(strcmp(mne,opmne)==0)
{
fclose(ftab);
fscanf(fsym,"%s%s",symadd,symtab);
while(!feof(fsym))
{
if(strcmp(operand,symtab)==0)
{
fprintf(fout,"^%s%s",op,symadd);
break;
}
else
fscanf(fsym,"%s%s",symadd,symtab);
}
break;
}
else
fscanf(ftab,"%s%s",opmne,op);
}
if((strcmp(mne,"BYTE")==0)||(strcmp(mne,"WORD")==0))
{
if(strcmp(mne,"WORD")==0)
fprintf(fout,"^00000%s",operand);
else
{
fprintf(fout,"^");
len=strlen(operand);
for(i=2;i<len-1;i++)
{
fprintf(fout,"%d",operand[i]);
}
}
}
fscanf(fint,"%s%s%s%s",add,label,mne,operand);
ftab=fopen("optab.txt","r");
fseek(ftab,SEEK_SET,0);
}
fprintf(fout,"\nE^00%s\n",start);
fclose(fint);
fclose(ftab);
fclose(fsym);
fclose(flen);
fclose(fout);
}
